# replace .war with .ear or the following for WARFILE if needed
# JARFILE=$(find ./build/libs -type f -wholename "*.jar" ! -wholename "*javadoc*" ! -wholename "*groovydoc*" ! -wholename "*sources*")
name: Whitesource Prioritize Java with Gradle

on: workflow_dispatch

jobs:
  spotless:
    name: Spotless

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Spotless
        run: ./gradlew spotlessCheck

  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - "1.8"
    steps:
      - uses: actions/checkout@master

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64

      - name: Tweak gradle.properties for Java 1.8
        if: ${{ matrix.java-version == '1.8' }}
        run: sed -e '/--add-exports/ s/^#*/#/' -i gradle.properties

      - name: Display version
        run: ./gradlew --version

      - name: Build artifacts
        run: ./gradlew assemble

      - name: Start stripe-mock
        run: docker run -d -p 12111-12112:12111-12112 stripe/stripe-mock && sleep 5

      - name: Run test suite
        run: ./gradlew check

      - name: WhiteSource Unified Agent Scan
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          WS_APIKEY: ${{secrets.APIKEY}}
          WS_USERKEY: ${{secrets.USERKEY}}
          WS_WSS_URL: https://app.whitesourcesoftware.com/agent
          WS_PRODUCTNAME: GH_${{github.event.repository.name}}
          WS_PROJECTNAME: ${{github.ref}}_Prioritize
          WS_ENABLEIMPACTANALYSIS: true
          WS_REQUIREKNOWNSHA1: false
          WS_RESOLVEALLDEPENDENCIES: false
          WS_GRADLE_RESOLVEDEPENDENCIES: true
          WS_GRADLE_AGGREGATEMODULES: true
          WS_GRADLE_PREFERREDENVIRONMENT: wrapper
          WS_GRADLE_WRAPPERPATH: ./gradlew
          WS_FILESYSTEMSCAN: false
          WS_GENERATEPROJECTDETAILSJSON: true
        run: |
          curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
          echo Unified Agent downloaded successfully
          WARFILE=$(find ./build/libs -type f -wholename "*.jar")
          echo $WARFILE will be added to appPath
          java -jar wss-unified-agent.jar -appPath $WARFILE -d ./
